ndlib/marble-blueprints

README.md
deploy/cloudformation/iiif-service-pipeline.yml
deploy/cloudformation/iiif-service.yml
deploy/cloudformation/iiif-webcomponent-pipeline.yml
deploy/cloudformation/iiif-webcomponent.yml
deploy/cloudformation/pipeline-monitoring.yml

4f61525aa476144bd564e9e39af95533dcaea372
This adds a new pipeline-monitoring template that will add CloudWatch event rules for the state changes of a pipeline that we care about. Ideally we'll be able to use this against any pipeline that follows our CI/CD stages of Source, Build, DeployToTest, Approval, and DeployToProduction. There are 3 rules that observe at the pipeline level, and the rest are at the stage level (see [Detect and React to Changes in Pipeline State with Amazon CloudWatch Events](https://docs.aws.amazon.com/codepipeline/latest/userguide/detect-state-changes-cloudwatch-events.html)).
Pipeline-level events:
- When the pipeline starts, it will email that a build has started and will attempt to deploy to production
- When the pipeline successfully finishes, it will email a …

MEL-71: Add pipeline notifications to image-viewer pipeline

---

deploy/cloudformation/iiif-service.yml
deploy/cloudformation/pipeline-monitoring.yml

349a713525fe1f473fc8a801e050c7ed7a03ee7d
Changed references to the stack name to use the given pipeline name. This is not as friendly a name, but is also a little more accurate and less dependent on stack naming conventions.
An extra, unrelated change is to the default desired count of services to run for the image service. We are currently in a pattern of only ever using one, so the default was going against our current pattern.

ESU-675: Bugfix pipeline name

---

README.md
deploy/cloudformation/static-host-pipeline.yml
deploy/cloudformation/static-host.yml

bf4c2b6dbcb5b3375afdc39580b2dc79d5475a53
There are now two components that fall into the static host pattern: the iiif web component, and the mellon-website. Changed the iiif-web-component templates (including the pipeline) to be a bit more generic so that we can reuse them for any components that require static hosting. Changes related to this:
- Parameterized the pipeline to allow for specifying the repo to watch, the source scripts for the build process, and the directory to copy built artifacts from
- Changed the parameters for the pipeline to use stack names to find the exports for the target buckets and urls. This is to reduce the number of parameters that need to be overridden. It unfortunately creates an export dependency, so if this causes problems we'll have to change. Would …

MEL-89: Create infrastructure for new static website assets

---

deploy/cloudformation/iiif-service-pipeline.yml
deploy/cloudformation/iiif-service.yml

a41c3198bd5892a3801bf1725c9a138a447d8174
The specs now require the protocol to be passed via the newman env. Updated the QA stage in the pipeline to match this change. Additionally, tweaked the target group in iiif-service.yml to allow faster registration/deregistration. This should speed up deployment times by approx 5 minutes.

MEL-70: Add protocol to specs

---

LICENSE

This license is approved by General Counsel and is the acceptable
and license agreed upon license for contributes to the Samvera project.
As one of the deliverables of the grant is to share this work with a
community, and seek community adoption and contribution, we want to
ensure that we are taking steps towards a community to which we have
an ongoing relationship with.
See [Samvera Community Intellectual Property Licensing and Ownership][1]
for further details.
[1]:https://wiki.duraspace.org/display/samvera/Samvera+Community+Intellectual+Property+Licensing+and+Ownership

Adding APACHE 2 license

---

README.md
deploy/cloudformation/app-infrastructure.yml
deploy/cloudformation/export-existing-network.yml
deploy/cloudformation/iiif-service-ci.yml
deploy/cloudformation/iiif-service-pipeline.yml
deploy/cloudformation/iiif-service.yml
deploy/cloudformation/network.yml
deploy/cloudformation/static-host-pipeline.yml
deploy/cloudformation/static-host.yml

Because CloudFormation will propagate tags at the stack level down to the resources within the stack, we do not need to have tags at each resources, nor do we need parameters to define these tags.
This PR cleans up the parameters, resource-level tags, and updates the README to reflect this.
There is also a feature enhancement in the [network.yml](https://github.com/ndlib/mellon-blueprints/blob/ESU-733-remove-unneeded-tags/deploy/cloudformation/network.yml) stack which adds a differentiator to the Subnets and NAT Gateways by creating a custom "Name" tag for each of these resources. Without this, they appear with the same name and are difficult to tell apart within the console. 
Credit to @hanstra for suggesting that fix.

ESU-733 remove unneeded parameters for tags and update README with new commands

---

deploy/cloudformation/iiif-service.yml

I want to deploy the stack to test lib nd but do not want dns for the image viewer.  
This allows us to use the default domain for the load balancer if there is no dns.

Change to use the load balancer if there is no service url.

---

deploy/cloudformation/iiif-service-pipeline.yml

Added -k to the newman tests when in a dev environment.  This stops the validation of the cert from causing a failure.

Update cloud formation to fix tests run in dev

---

deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/manifest-pipeline.yml

- Other pipeline templates allow users to specify the stack names for the targeted test/prod stacks, instead of inferring based on AppName. Changed this to match
- Removed hard coded references to "mellon-*" resources. This only worked because stacks will create resources using stack name when a name is not specified (for most resources), and makes a lot of assumptions that stack names begin with "mellon-pipeline"
- Changed policy to be a bit more restrictive on what resources the pipeline can modify via CloudFormation. We have to be a bit careful here while we're doing CD for these pipelines. Now that this one can create resources, a compromised repository could do bad things to our AWS account. I did still want to strike a balance between explicitly defining what resources it could …

Pipeline cleanup to match other pipeline conventions

---

deploy/cloudformation/manifest-pipeline.yml

This change is to try to bring the project in line with the guidelines for ssm parameters and use of configurations.  
The other params were removed because there is no current need to have those options be configurable.  Therefore they do not count as SSM configs.  
I decided to copy config keys from other stacks over based on the suggestion from @jgondron

Update SSM param configuration to only use the ssm parameters from other stacks.

---

deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/manifest-pipeline.yml

These changes started because I was having trouble deploying likely because I had changed the logical name of an ssm key but not the path associated with it.  
But the main reason that they were done is that we wish to separate ssm key associated with application configuration and those that are used for stack infrastructure in the ssm path key.  So I moved my config oriented params to the config path location.

Fixed the ssm deploy issues and changed to use the correct app config path for ssm

---

deploy/cloudformation/manifest-pipeline.yml

Adds AWS SES permissions to lambda execution role so that the finalize lambda can send out an email notification stating the manifest pipeline job completed.  Note that there is no 'Resource' to restrict it has to be all.

ses permissions

---

deploy/cloudformation/manifest-pipeline.yml

Memory: 512 MB
Timeout: 10 min
To account for a large number of files that are copied at the end of the process cycle

Increase memory and timeout for FinalizeLambdaFunction

---

README.md
deploy/cloudformation/unified-static-host.yml

The main site is not handling deeplinking due to the CloudFront/S3 default behavior. This PR will add a Lambda and IAM for the Lambda, allowing deeplinks to resolve as well as other known paths in the SPA.
The README has also been updated to identify that there is now a separate CloudFormation for the main Mellon website - this is done because as of now, we have not identified that we want to have the redirection behavior on other static page solutions, such as the webcomponent.

Redirection and deep linking for unified site

---

deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/manifest-pipeline.yml

To do this I added an edge lambda that detects if the index.json is not being looked for.  
As a side note this is intended to work specifically with the mellon url architectures which always have directories with an index.json file in them other file patterns are not supported. 
I updated the manifest bucket to not have a website associated with it anymore.

Fix cloud front detection of default directory file.

---

deploy/cloudformation/manifest-pipeline.yml

This code addresses the public bucket access issue for the manifest pipeline in two ways:
1. Allows the `Authorization` header to the whitelist of headers to be forwarded through the CloudFront.
1. Adds `s3:GetBucketCors` policy to the Manifest Bucket's Bucket Policy that is granted to the CloudFront to allow the CloudFront to read CORS configuration.

update bucket policy and add authorization header forwarding

---

deploy/cloudformation/manifest-pipeline-pipeline.yml

Ran into a few issues with permissions when propping this up from scratch:
- The cloudformation needs to be able to read/put ACL on the log bucket (using the root name). Broke this out into its own permission since the Cloudformation does not need permissions to do all of the other stuff to the log bucket
- It needs permissions to add tags to the state machine
- No longer needs put/delete bucket website since the manifest pipeline now has a clouddfront in front of the bucket

Fix pipeline permissions

---

README.md
deploy/cloudformation/app-infrastructure.yml
deploy/cloudformation/domain.yml
deploy/cloudformation/iiif-service.yml
deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/manifest-pipeline.yml
deploy/cloudformation/static-host.yml
deploy/cloudformation/unified-static-host.yml

This change adds the ability to optionally create a zone in Route53, and a record for the manifest-pipeline and unified-static-host stacks, in order to better automate the creation of a valid hostname and certificate. Summary of changes:
- Changed `manifest-pipeline.yml` and `unified-static-host.yml` to allow for the optional create of a RecordSet in Route53
- Separated the creation of the ACM and zone into a `domain.yml`. This can optionally skip the creation of the zone to only create the wildcard cert for the domain/subdomain. Note: this still assumes we’re continuing with a single wildcard cert for each subdomain for now. ACM was previously created in app-infrastructure, but this will allow for creating separate subdomains for different grouping of services, ex: `*.domain.com` and …

Add DNS to manifest pipeline

---

deploy/cloudformation/app-infrastructure.yml
deploy/cloudformation/data-broker.yml
deploy/cloudformation/iiif-service-ci.yml
deploy/cloudformation/iiif-service-pipeline.yml
deploy/cloudformation/static-host-pipeline.yml

I ran our Mellon templates through [CFN_Nag](https://github.com/stelligent/cfn_nag), which is a Ruby gem that runs some checks against CloudFormation templates. 
I updated the CloudFormation templates to either address the failures reported, or added some Metadata to the template in order to confirm that the behavior was acceptable based on our use-case.
I also parameterized the names of the iiif-service-pipeline CodeBuild resources, as these were hard-coded and meant we could only spin one instance of the pipeline up per region.

Update to IAM Permissions

---

README.md
deploy/cloudformation/app-infrastructure.yml
deploy/cloudformation/domain.yml
deploy/cloudformation/iiif-service-pipeline.yml
deploy/cloudformation/iiif-service.yml
deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/manifest-pipeline.yml
deploy/cloudformation/static-host-pipeline.yml
deploy/cloudformation/static-host.yml
deploy/cloudformation/unified-static-host.yml

Now that we’ve landed on a domain stack to handle domains/subdomains, the SubDomain parameter in all of the service stacks will only ever be prefixes. This primarily changes the naming of the SubDomain param to HostnamePrefix, with a few other pieces of cleanup. Changes:
**domain.yml:**
- Added additional language to the domain template to be clear that it will handle either domain or subdomains for the services built on top of it
**iiif-service.yml:**
- Changed to use HostnamePrefix, and also changed things like URL to hostname. The URL export/ssm are hold over from older templates and aren’t really reflective of the type of value thats being exported
- Cleaned up some overlap with how the hostname was both exported and added to ssm. Removed the export and fixed the pipeline to read from …

Change naming of DNS parameters

---

deploy/cloudformation/manifest-pipeline-pipeline.yml

This addresses a minor issue in the v2019.2 pre-release where the CodeBuild was not respecting the `InfrastructureStackName` parameter from the manifest-pipeline-pipeline.yml and resulted in it only being possible to deploy one instantiation of the manifest-pipeline-pipeline.yml stack.

update the buildspec to use the InfrastructureStackName parameter

---

deploy/cloudformation/iiif-service-pipeline.yml
deploy/cloudformation/manifest-pipeline-pipeline.yml

During yesterday's deploy, encountered a few issues with building everything back up. The image service pipeline was unable to read from SSM for the prod host name when posting to github. Additionally, when deploying without creating the dns zone, the domain stack will not have a Zone export. This currently breaks the manifest code pipeline. Had to remove this dependency to get it working. We need to revisit this, but the best solution I could determine to work with both paths is to just allow all. This should not be a security issue in our production account for now, since the code pipeline is not creating DNS record sets, but we'll want to fix this before we redeploy to our development account.

Bug fixes related to rebuild

---

deploy/cloudformation/manifest-pipeline-pipeline.yml

Now that the configuration repo’s name has changed, updating the default in the manifest deployment pipeline.

Mellon to marble name change

---

deploy/cloudformation/export-existing-network.yml

This template is creating an SSM resource with a constant path, meaning we can't deploy another instance of this template without destroying others. Changed to namespace it by stack name.

Fix network template path collision

---

deploy/cloudformation/manifest-pipeline-pipeline.yml

The recent redeploy required first deploying with a dummy hostname prefix, then redeploying with the new one once dns was changed. This caused the manifest deployment pipeline to remove tags and change ssm parameters, which hit unforeseen permissions issues. This change fixes the immediate issues I encountered.

Fix ssm permissions on Manifest Pipeline

---

deploy/cloudformation/manifest-pipeline.yml

For the CurateND Image Viewer integration, we discovered that the headers being sent by the application were not the `Authorization` headers being used elsewhere, but rather were `X-CSRF-Token`.
This updates the Manifest bucket to allow these CORS headers so Curate can show the ImageViewer in an iFrame.

adding additional CORS header for Curate integration

---

deploy/cloudformation/manifest-pipeline-pipeline.yml

The CodePipeline is currently in a broken state due to the inability to update the State Machine for Step Functions. 
Breaking changes took place with #70 and the changes to the step functions.
This PR will add the needed permissions to allow the trust role to update the State Machine and allow the Code Pipeline to finish.

add IAM permissions for step function updates

---

README.md
deploy/cloudformation/iiif-service-pipeline.yml
deploy/cloudformation/manifest-passthrough-pipeline.yml
deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/static-host-pipeline.yml

This changes all pipelines to ensure that any QA and Approval steps are grouped within the same stage as the Deploy to the test environment. This will prevent an integrity issue that can occur if multiple invocations of the pipeline happen before the Approver can visit the test site.
- Changed IIIF service deployment pipeline to group Deploy/QA/Approval into one stage.
- Changed static-host-pipeline to group the deploy/approval actions under a test stage
A few additional cleanups/fixes:
- Found a new reference to mellon in the README and changed to marble
- Changed default production stack names to include a -prod suffix to better match how we are now deploying these stacks
- Renamed several stages and actions to be more consistent across the different pipelines
- Fixed an issue with …

Group Approval with Test deployment stages

---

README.md
deploy/cloudformation/iiif-service-pipeline.yml
deploy/cloudformation/manifest-passthrough-pipeline.yml
deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/static-host-pipeline.yml

- Added parameter to the iiif-service-pipeline to retrieve the host names of the target stacks and added links to the repo and test/prod services in the approval message
- Added links to the repo and to the test/prod stacks in the approval message for the manifest services. These don't really have endpoints to review, so this is the best we can provide for now.
- Added links to the repo and to the test/prod stacks in the approval message for static host pipelines
Additional changes:
- Fixed a few naming problems in the readme associated with the image viewer
- The previous PR https://github.com/ndlib/marble-blueprints/pull/73 changed the source step names, but the artifact names that are passed around in the pipeline no longer matched those steps. Changed the artifact names to more …

Add better links to the approval messages

---

deploy/cloudformation/unified-static-host.yml
src/unifiedEdgeLambda/handler.js
src/unifiedEdgeLambda/handler.test.js

These are changes to the Cloudfront configurations needed for the pipeline to deploy the Gatsby version of the Marble Website: https://github.com/ndlib/marble-website-starter
* Changes to the `src/unifiedEdgeLambda/handler.js` are copied from https://github.com/ndlib/esu-cloudformation/tree/master/lambda-edge-utils including tests.
* Added custom 404 page handling to `unified-static-host.yml`

SPA to Gatsby changes

---

deploy/cloudformation/static-host-pipeline.yml

Missed a pipeline change related to https://github.com/ndlib/marble-blueprints/pull/75. Changed static-host-pipeline.yml to export the approval topic to make it easier to bind monitoring and slack approvals

Fix exports

---

deploy/cloudformation/manifest-pipeline-pipeline.yml

The manifest CodePipeline wasn't pointing the task definition to the full URI of the ECR image that it built.

Fix task definition

---

deploy/cloudformation/app-infrastructure.yml
deploy/cloudformation/iiif-service.yml

This is a hotfix to get the deployment to work. This adds a bucket policy to the shared log bucket to allow the ALB to write access logs. For now this will only work when the image service is deployed to us-east-1. This additionally extends the timeout between the ALB and Cantaloupe based on testing performed when rendering large images. This will likely need to be reassessed once we determine the sizes we will support.

Fix Image Service access logs

---

deploy/cloudformation/manifest-pipeline.yml

This gives the DataAdmin role the ability to write/delete to both the process and manifest buckets in the manifest-pipeline.

Add write/delete permissions for DataAdmin

---

deploy/cloudformation/manifest-pipeline.yml

To have a better more sustainable namine structure.
Related to: https://github.com/ndlib/marble-manifest-pipeline/pull/77

Renamed the pipeline variables and directories

---

deploy/cloudformation/manifest-pipeline.yml

This does 2 things.
Changes the step functions so that they call the schema creation in the order needed to create the schema first and second to process it to a manifest
Add the mets processing step functions
3.!! added the permissions for the step functions to call the schema step functions

Add Mets Step functions and schema processing step functions

---

README.md
deploy/cdk/.gitignore
deploy/cdk/.npmignore
deploy/cdk/README.md
deploy/cdk/bin/base.ts
deploy/cdk/cdk.json
deploy/cdk/jest.config.js
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cdk/lib/iiif-serverless/index.ts
deploy/cdk/lib/namespaced-policy.ts
deploy/cdk/package-lock.json
deploy/cdk/package.json
deploy/cdk/test/iiif-serverless/deployment-pipeline.test.ts
deploy/cdk/tsconfig.json
deploy/cdk/tslint.json
deploy/cloudformation/iiif-serverless-cdn.yml
docs/iiif-image-service.md

This adds a deployment pipeline that will deploy the app using the provided template.yml in the app repo. This also adds a new CloudFormation that will create a CustomDomain for the API so that our hostnames and certs will match. Creating this in cdk would have made an odd mix between the two. In the future, we'll want to refactor to use a cdk based stack for the application as well, so I'm assuming it will be easier to rewrite this part at that time.
I'm putting this cdk code at the root of the deploy/cdk directory. Personally, I think this should be a multistack cdk application so that on deploy you can just choose which components (stacks) you want to deploy. In addition, doing it as a multistack application will let cdk take care of a lot of the cross-stack property sharing for us …

Create deployment for nulib/iiif-serverless

---

deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts

Changed deployment pipeline to not import the Route53 zone from the domain stack when not creating a DNS recordset, since in this context the domain stack probably doesn't manage a zone.

Fix reliance on Zone from domain stack

---

deploy/cloudformation/manifest-pipeline.yml

Each lambda has been assigned fine-grained permissions rather than a blanket role accommodating for all.

MEL-574 single role moved to granular policies

---

deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/primo-passthrough-pipeline.yml
deploy/cloudformation/static-host-pipeline.yml

Added commit message and a url to the changes to the approval message in all pipelines based on cloudformation. We'll have to wait a bit until cdk supports the namespace property of actions (https://github.com/aws/aws-cdk/issues/5219) before we can change those.
Reference: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html#reference-variables-list

Add commit info to approvals

---

deploy/cdk/lib/user-content/index.ts

* Previously the unique identifier for users was the user `netid`. This  would become problematic when we implement alternative login methods such as Facebook or Google later on. 
* To remedy this the unique identifier will be changed to a hash value of the `sub` and `iss` fields on the user token. 
* Most of the needed change will take place in the Marble User Content lambda code, but we need an additional `GET` endpoint for the API and an additional secondary global index on the user table to continue being able to look up users by `userName`.
The associated Lambda changes are here: https://github.com/ndlib/marble-user-content/pull/5

MARBLE-678 Change Unique Identifier for Users

---

deploy/cdk/bin/base.ts
deploy/cdk/lib/user-content/deployment-pipeline.ts
docs/user-content.md

Pipeline can now add an optional email notification anytime state
changes. Also fixed an issue with propagating cors headers down to the
deployed stacks.

Add pipeline email notifications and cors header

---

deploy/cloudformation/static-host-pipeline.yml

The use case here is to allow us to run an additional step prior to production deployment. We currently update test/production with auxiliary data in a single build step, however, if after deploying to test the build is rejected we have already deployed data to production. This additional build step resolves that.

add pre-deploy prod step 

---

deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/manifest-pipeline.yml

Replaced references to RBSCS3ProdImageBucketArn and RBSCS3TestImageBucketArn with RBSCS3ImageBucketName
Need to change deploy parameters from passing:
RBSCS3ProdImageBucketArn=arn:aws:s3:::libnd-smb-rbsc \
  RBSCS3TestImageBucketArn=arn:aws:s3:::libnd-smb-rbsc
To passing:
RBSCS3ImageBucketName=libnd-smb-rbsc

changes related to rbsc-image-bucket

---

src/unifiedEdgeLambda/handler.js

`webp` is a "next generation" image format. SEO tools like to see it instead of older formats.

Update handler.js to include .webp as a valid format

---

deploy/cloudformation/manifest-pipeline.yml

I'm leaving the role definition in tact in AllowStepFunctionLoggingPolicy.
Removed logging from StateMachineCreateCSVs to try to get this to run the pipeline deploy in production.  Then will come back and re-add.

temporarily removed logging from StateMachineCreateCSVs

---

deploy/cloudformation/manifest-pipeline.yml

When I copied the permissions for putting I forgot the second version of the resource needed for s3.

update permissions with missing resource

---

deploy/cloudformation/manifest-pipeline.yml

Added ArchivesSpaceExportLambdaFunction
Added call to this lambda to StateMachineCreateCSVs.
Note:  This lambda creates nd.json for  ArchivesSpace content, regardless of the existance of a DOA record.  After manifest creation is changed to use nd.json, we can remove HarvestEADsLambdaFunction.

Added ArchivesSpaceExportLambdaFunction

---

deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cloudformation/static-host-pipeline.yml

The problem. 
We are deploying the test artifacts built for test to prod and it seems like it is causing us to point at the test instance of elastic search.  no matter how hard we try to fix it... 
This creates a new output artifact similar to what the test build does.  
Then it uses that in the deploy instead of the name of the output artifacts from the test build.

this is what i think is wrong in the pipeline

---

deploy/cloudformation/manifest-pipeline.yml

* Added permissions for museum_export lambda to list, read, and delete files on process bucket so it can loop between iterations and retain state.

Let museum_export list, read, and delete file on process bucket

---

deploy/cloudformation/manifest-pipeline-pipeline.yml
deploy/cloudformation/manifest-pipeline.yml

* Changed manifest-pipeline-pipeline.yml
* Added events:RemoveTargets permission to CloudFormationRolePolicy
* Also added resource StartHarvestAndCreateStandardJsonRule to allow me to rename the old rule from StartHarvestAndCreateCSVRule to StartHarvestAndCreateStandardJsonRule.
* Changed manifest-pipeline.yml
* renamed StartHarvestAndCreateCSVRule to StartHarvestAndCreateStandardJsonRule to describe what is now does.
* removed "events:RemoveTargets" from FargateTaskPolicy where I had put it before incorrectly.

Fix manifest-pipeline deploy failure

---

deploy/cdk/bin/base.ts

We have several key value pairs in our context that are directly mapped
to stack props. These kvp are namespaced as "namespace:key". I found a
way to get all context from an env variable so that we can just glob all
of these and pass them into the stacks. This should make it cleaner and
easier to add new context/props to stacks.

Change namespaced context handling

---

deploy/cdk/bin/base.ts

Because it wants an environment name string.

Fix es stack

---

deploy/cdk/bin/base.ts
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts

This changes the deployment pipeline for serverless-iiif to use cdk
instead of cloudformation.

IIIF Serverless Pipeline

---

deploy/cdk/bin/base.ts
deploy/cdk/bin/codepipelines.ts
deploy/cdk/bin/services.ts
deploy/cdk/cdk.context.json
deploy/cdk/lib/context-env.ts
deploy/cdk/lib/context-helpers.ts
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts
deploy/cdk/lib/user-content/deployment-pipeline.ts

Developing and deploying cd pipelines is a different type of activity
from developing and deploying the service stacks. In addition to this,
we are now creating separate foundation stacks for test and prod, but not
specifically instantiating these stacks in the cdk app, which is an
anti-pattern. Putting all of these things in base.ts was becoming harder
to parse and understand. This is an attempt at separating these types of
activities. The idea is that you will now have to pass an additional
context variable called `stackType`. The available stacks to deploy will
depend on what is given for this context variable, either `service` or
`pipeline`. `service` will be the default to retain backward compatibility
with both devs and pipelines.
Here's the output of `cdk list` as an example:
```
$ …
```

Separate services from pipelines

---

deploy/cdk/lib/static-host/deployment-pipeline.ts

This fixes the pipeline to override the correct context for the instance that it's deploying.

Fix context override for static host pipelines

---

deploy/cdk/bin/services.ts
deploy/cdk/cdk.context.json
deploy/cdk/lib/image-processing/deployment-pipeline.ts
deploy/cdk/lib/image-processing/images-stack.ts
deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts

- Changed image processing pipeline to get manifest pipeline bucket names
from other stacks instead of requiring them via context
- Changed image processing to use the env config to get the rbsc bucket
since that changes per env
- Fixed an issue with the target stack names. We had changed them from
`marble-image` to `marble-image-processing` but had missed updating the
pipeline to use these names when deploying.
- Fixed an issue with the code terminating too soon during synth,
preventing cdk from seeing dependencies correctly. We need to find an
alternative solution to the `if !fs.existsSync(props.lambdaCodePath); return`
checks that still allow the code to continue, but still throws an error
when that stack is deployed. In this specific case, cdk was not seeing
the dependency between …

Fix issues in image processing CD pipeline

---

deploy/cdk/bin/codepipelines.ts
deploy/cdk/cdk.context.json
deploy/cdk/lib/cdk-pipeline-deploy.ts
deploy/cdk/lib/elasticsearch/deployment-pipeline.ts
deploy/cdk/lib/elasticsearch/elastic-stack.ts
deploy/cdk/lib/namespaced-policy.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts

This further automates deployment by sharing the ES endpoint and index
name with the rest of the app. The endpoint will now be added to ssm
by the elasticsearch stack, which will be injected into the env of
the website CodeBuild as SEARCH_URL. This alleviates the need to manually
create the `/all/static-host/marble-test-website/search_index` and
`/all/static-host/marble-test-website/search_url` parameters.

Fix search url

---

deploy/cdk/bin/codepipelines.ts
deploy/cdk/lib/elasticsearch/deployment-pipeline.ts
deploy/cdk/lib/foundation/index.ts
deploy/cdk/lib/foundation/pipeline-foundation-stack.ts
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cdk/lib/image-processing/deployment-pipeline.ts
deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts
deploy/cdk/lib/user-content/deployment-pipeline.ts

To limit the number of buckets, added a pipeline foundation stack that
creates a shared artifact bucket and changed all pipelines to use the
shared bucket.

Shared pipeline bucket

---

deploy/cdk/cdk.context.json

We are aiming to deploy all of these cdk stacks prior to destroying the
old stacks that were created by cloudformation. The only way to do this
is to use a different set of stack names. Changing the default namespace
to `marbleb` to allow for this.

Change stack names to deploy in parallel

---

deploy/cdk/lib/user-content/deployment-pipeline.ts
deploy/cdk/lib/user-content/user-content-stack.ts

This adds a stage that will add the test data for us prior to running
smoke tests. This also meant changing the user-content stacks to output
the table names to ssm so that we could inject them into the pipeline
at execution time.

Further automate user content tests

---

deploy/cdk/lib/namespaced-policy.ts

Opening up this tags permissions. Was causing problems during the change
of the cnames for the APIs

Fix issue with permissions for cname change

---

deploy/cdk/bin/codepipelines.ts
deploy/cdk/cdk.context.json
deploy/cdk/lib/context-env.ts
deploy/cdk/lib/elasticsearch/deployment-pipeline.ts
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cdk/lib/image-processing/deployment-pipeline.ts
deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts
deploy/cdk/lib/types.ts
deploy/cdk/lib/user-content/deployment-pipeline.ts

Github has a 20 webhook limit per project. We need to limit webhooks to
production pipelines only. Polling should be sufficient in dev.

Change dev to use polling instead of webhooks

---

deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts

The export from the image api is being interpreted by the metrics stack
as the literal export name instead of importing its resolved value.
Unfortunately, API name can't be easily exported. This value is set to
the literal of 'stackname-api' in the source template (see https://github.com/nulib/serverless-iiif/blob/c21120643e199dbf4b342ba1427dd4aab7e11ea6/template.yml#L107).
Changed the stack to share this as the same literal. Also removed it as
an export since this is available at synth time.
Additionally, the source template has an existing export for ApiId at (see https://github.com/nulib/serverless-iiif/blob/c21120643e199dbf4b342ba1427dd4aab7e11ea6/template.yml#L387)
so added an exposed property where when used will import this value from
the api stack.

Fix IIIF Image metrics

---

deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts

* Fixed bugs on granting dynamo access for various lambdas to grant access to the correct lambdas.
* Added dataExtensions dynamo table (for use by Red Box).
* Added point-in-time recovery to dynamo tables.

Create dataExtensions dynamo table

---

deploy/cdk/lib/image-processing/images-stack.ts

Attempting to resolve out of memory error - STOPPED (OutOfMemoryError: Container killed due to memory usage)

bump memory from 512 to 1024

---

deploy/cdk/lib/static-host/static-host-stack.ts

Fixed the 403 error code and added a new one for 404.  
This fixes 404 error problems and fixes the problems we were having with dynamic routes not rendering. 
As a note:  
Dynamic routes are reporting themselves as 404s to fix this we would need to do edge lambda work.  My guess is that this is ok until we need to index in a search engine dynamic content on the site.

update error codes in cloud front

---

deploy/cdk/lib/static-host/deployment-pipeline.ts

* Now correctly pass parameters as website:parametername instead of just parametername.
* Fixed smoke test to use correct domain if it is overridden.

Fixed passing optional parameters

---

deploy/cdk/README.md
deploy/cdk/package.json
deploy/cdk/yarn.lock

This bumps the version of the ndlib-cdk module to pull in a fix to the
calculation of availability for Elasticsearch. Also added instructions
to the readme on how to deploy the SLO stack.

Fix Search API SLOs

---

deploy/cdk/lib/maintain-metadata/deployment-pipeline.ts

Added permissions to allow maintain-metadata-deployment stack to correctly deploy the maintain-metadata stack

Marble 1357 update maintain metadata

---

src/unifiedEdgeLambda/handler.js
src/unifiedEdgeLambda/handler.test.js

The updates to gatsby-plugin-image now can generate .avif images along side of webp images for images sets that browsers can choose from when rendering.  
Add the extension in so that they are able to be sent from the site.

Update to allow avif images to be sent from the site.

---

src/unifiedEdgeLambda/handler.js
src/unifiedEdgeLambda/handler.test.js

The problem currently is that we have some dynamic routes and they are not getting routed to a file with the built site in it 
This solution checks for those routes and redirects to the root index file in the site. 
This solution is not configurable for any site to dynamically injecting its own dynamic routes.  
However,  since marble is the only site that has dynamic routes and it is the only site at the moment I know will have them.  We don't want to do more work than is required until we know what that work is.

update the edge lambda to route dynamic paths correctly

---

deploy/cdk/lib/namespaced-policy.ts

* ARNs will have the stackName truncated if the stackName plus logicalId gets too long.  I'm truncating the stack name to 25 characters to accommodate abbreviated stack name in some ARNs.

Fix Rule Privilege

---

deploy/cdk/cdk.context.json

Removing the Duty Officer email for now while this is in beta. Will
change this back once we officially launch. These will continue to go
to Rob and he will notify developers of issues.

Change SLO email

---

deploy/cdk/README.md
deploy/cdk/bin/services.ts
deploy/cdk/cdk.context.json
deploy/cdk/lib/multimedia-assets/index.ts
deploy/cdk/lib/multimedia-assets/multimedia-assets-stack.ts
deploy/cdk/test/multimedia-assets/multimedia-assets-stack.test.ts

This creates a simple s3 bucket and a CloudFront. Public access to the s3 bucket is blocked, so they must be accessed through the CloudFront. CORS headers restrict access to the same domain as the cloudfront CNAME.
I didn't write a pipeline for this yet for a few reasons:
- We may only want one bucket to share between test and prod, similar to how the rbsc bucket is set up. (Not 100% sure on this.)
- We don't have a place to fetch content _from_ and put it in the bucket, so there wouldn't really be anything for the pipeline to monitor for changes. Sure, it could redeploy changes to the stack itself, but that sort of leads into the next one...
- Maybe this could be folded into another stack, like image-processing? It stands to reason that all assets (images/video/audio) would share …

Add stack for hosting audio and video content.

---

.github/workflows/ci.yml
deploy/cdk/test/manifest-pipeline/stack.test.ts

Without sanity CI in our repository, there exists a chance that merged code will be unable to be built. This basic CI should help mitigate this concern by building the codebase on push as well as when a pull request is opened.
Closes ESU-1646

ci(github-actions): add build and testing to CI

---

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts
deploy/cdk/test/maintain-metadata/stack.test.ts

I'm not sure if we need the API key stuff at all, but at least making OIDC the default seems like a solid choice. I had issues with getting it to authorize using OIDC when API Key was the default, but it seems with them swapped, both methods work fine.

MARBLE-1637 Make OIDC default authorizer for app sync api.

---

deploy/cdk/bin/services.ts

This API is being refactored to use AppSync queries instead of an API GW.
We don't have a way to create SLOs using an AppSync SLI yet, so silencing
this until we have that implemented (https://jira.library.nd.edu/browse/ESU-1694)
and the AppSync work is complete (https://jira.library.nd.edu/browse/MARBLE-1665).

Silence User Content API alarms

---

deploy/cdk/bin/services.ts
deploy/cdk/cdk.context.json
deploy/cdk/lib/context-env.ts
deploy/cdk/lib/image-processing/images-stack.ts
deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts
deploy/cdk/lib/maintain-metadata/schema.graphql
deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts
deploy/cdk/lib/multimedia-assets/multimedia-assets-stack.ts
deploy/cdk/lib/user-content/user-content-stack.ts
deploy/cdk/package.json
deploy/cdk/test/maintain-metadata/stack.test.ts
deploy/cdk/test/manifest-lambda/stack.test.ts
deploy/cdk/test/manifest-pipeline/stack.test.ts
deploy/cdk/test/multimedia-assets/multimedia-assets-stack.test.ts
deploy/cdk/yarn.lock

Several changes were made to maintain-metadata:
* Add types to schema: Media, MediaGroups, Image, and ImageGroups
* Add Queries: getMedia, getMediaGroup, getImage, getImageGroup, listImageGroups, listImageGroupsByStorageSystem, listImageGroupsForS3, listMediaGroups, listMediaGroupsByStorageSystem, listMediaGroupsForS3.
* Add mutation saveImageGroupForWebsite
* Modify mutation saveDefaultImageForWebsite
* Add defaultImage, images, mediaGroupId, media, and mediaGroupId to ItemMetadata
* Added "root" element to ItemMetadata that points to the root of the collection.  Null if the item is the root of the collection.
multimedia-assets was modified to reference marbleContentBucketName, transitioning from rBSCS3ImageBucketName.  Note:  this will use existing buckets testlibnd-smb-test and …

Marble 1662 modify app sync to accommodate new image and media structures

---

deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts

* Bumped memory size from default of 128 to 1024 to speed lambda execution from around 3 seconds to around half a second.

Bump manifest-lambda resources

---

deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts

* explicitly pass "true" or "false" to createCopyMediaContentLambda, instead of passing an empty string to be coerced to false.

Fix manifest deployment

---

deploy/cdk/bin/codepipelines.ts
deploy/cdk/bin/services.ts
deploy/cdk/cdk.context.json
deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts
deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts
deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts
deploy/cdk/lib/static-host/pipeline-s3-sync.ts
deploy/cdk/package.json
deploy/cdk/test/manifest-lambda/smokeTests.json
deploy/cdk/test/manifest-lambda/stack.test.ts
deploy/cdk/test/manifest-pipeline/stack.test.ts
deploy/cdk/yarn.lock

* Added code to manifest-lambda stack to create a new public-graphql-lambda which will allow the unauthenticated caller to query one of these AppSync resolvers:  ['listPublicPortfolioCollections', 'listHighlightedPortfolioCollections', 'listPublicFeaturedPortfolioCollections', 'getExposedPortfolioCollection']. This will be used by the website to serve public portfolio content without exposing the GraphQL API Keys.
* Created a new API Gateway in front on this new lambda
* Added code to manifest-lambda deployment pipeline to pass an appropriate name for the new API Gateway
* Removed obsolete marble manifest CDN and associated SPA redirection lambda from marble-pipeline-stack
* Added smoke tests for new API Gateway

Marble 1793 create api gateway for public portfolios

---

deploy/cdk/cdk.context.json

Now that we're out of beta, need to send alarms to the Duty Officer list.

Fix SLO alarm email

---

deploy/cdk/lib/static-host/static-host-stack.ts

The bucket logs for static sites aren't being properly prefixed, causing
Athena queries to have to scan all static-site logs (very slow) when
looking for a single site. Added a / at the end to properly partition
by site name.

Fix bucket logging

---

deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts
deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts

`pyenv versions` will list the versions available, but crucially will not stop the execution flow if there is an error. This change uses `pyenv version` which will check the .python-version file and make sure it matches with the environment of the codebuild. If there is a mismatch, exit out and cause the codebuild to fail so we don't get sneaky errors in production. 😅

Fix python version checking

---

deploy/cdk/cdk.context.json

I don't know if we actually have Sentry logging enabled for this... But if we do, it would help to actually pass the value to the stack. 😄

Fix misnamed context value

---

deploy/cdk/lib/elasticsearch/deployment-pipeline.ts
deploy/cdk/lib/github-approval.ts
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cdk/lib/image-processing/deployment-pipeline.ts
deploy/cdk/lib/maintain-metadata/deployment-pipeline.ts
deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts
deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
deploy/cdk/lib/multimedia-assets/deployment-pipeline.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts
deploy/cdk/lib/user-content/deployment-pipeline.ts

**Move to using the ndlib-cdk provided newman runner**
This is to avoid using a custom image for our CodeBuilds. Newman in
particular is a relatively fast package to install at runtime, so it
shouldn't add a significant time to the execution of the pipelines.
**Normalize the approval messages**
Added a reusable construct for creating approval actions for pipelines
that are based on Github sources. Changed all pipelines to use this
construct instead of forming their own messages. The message could probably
use a little more iteration to make it more concise, but should be easier
to do so now that it's in one place. Here's an example of what it will
look like: [User content approval message](https://app.slack.com/block-kit-builder/T8C2X85T2#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22t …

Remove dependence on newman image and normalize approvals

---

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts
deploy/cdk/lib/maintain-metadata/schema.graphql

allow getUserPortfolio to return data if there is an API key
update the .collections to return public API if the user in the login API does not equal the source.portfolioUserId
update the getPortfolioCollection so that it checks if the API user in the token is the current owner of the record.

update the resolvers to take into account if the api key or open id connect token is sent to the profile resolvers

---

deploy/cdk/lib/static-host/static-host-stack.ts

This adds the `synthetics-timestamp` query parameter to the list of
forwarded values to the s3 origin. This is so that our synthetics can
force a cache miss on every request to better monitor availability and
latencies for origin requests.
Note: The additional `cookies: { forward: none }` is to preserve the
previous behavior after adding our own `forwardedValues`

Forward synthetics-timestamp param to origin

---

deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts
deploy/cdk/lib/monitoring/dashboards-stack.ts

This adds detailed dashboards for all serverless APIs and CloudFront
based CDNs. This additionally changes the manifest lambda apis to enable
detailed metrics. Without this, we won't get metrics per method in the
dashboards.
This does not yet add dashboards for the ElasticSearch and Graphql APIs,
since those do not exist in ndlib-cdk just yet. I've created placeholder
code for now to give an example of what that might look like once it's
added.
Also, added one missed label override for the multimedia assets cloudfront
in the summary dashboard.

Add detailed dashboards

---

deploy/cdk/lib/monitoring/dashboards-stack.ts

This adds a dashboard for the IIIF Image Service and fixes a copy/paste
issue with referencing the user portfolio api stage name.

Add IIIF Image Service Dashboard

---

deploy/cdk/lib/elasticsearch/elastic-stack.ts
deploy/cdk/package.json
deploy/cdk/yarn.lock

Made the following changes so the ElasticSearch stack will again deploy:
* Actually downgraded back to ElasticSearch 7.7
* Changed back from 3 nodes to 2 nodes (in production)
* Changed back from 't2.medium.elasticsearch' to 't2.small.elasticsearch'
Ultimately, to change these settings, we need to let CloudFormation define the name of the ElasticSearch domain, but we can't because of synthetics.
Instead, our solution will be to create a separate OpenSearch stack, and deploy that in parallel to ElasticSearch.  Once we update the static host sites to use OpenSearch, we can decommission the ElasticSearch stack.

Downgrade Marble ElasticSearch back to original settings

---

.github/workflows/ci.yml
deploy/cdk/lib/opensearch/deployment-pipeline.ts
deploy/cdk/lib/opensearch/opensearch-stack.ts

* Changed opensearch policy based on props.namespace instead of namespace
* Changed the number of opensearch data nodes to 4, since neither 2 nor 3 are valid options.

Fix OpenSearch Deployment

---

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts
deploy/cdk/lib/maintain-metadata/schema.graphql
deploy/cdk/test/iiif-serverless/iiif-serverless-stack.test.ts
deploy/cdk/test/maintain-metadata/stack.test.ts

* Added width and height to FilesToProcess and Image schemas
* Added height and width as parameters for Mutation.saveFileLastProcessedDate
* Created two new functions: saveFileToProcessRecord and updateImageRecord
* Modified the MutationSaveFileLastProcessedDateResolver to be a pipeline instead of a simple resolver, calling updateImageRecordFunction and saveFileToProcessRecordFunction
* Added tests for new functions

Add image width and height to AppSync

---

deploy/cdk/lib/maintain-metadata/deployment-pipeline.ts

* This is required to be able to delete a stack (in order to re-deploy)

Add permission to delete AppSync DataSource

---

deploy/cdk/package.json
deploy/cdk/test/foundation/stack.test.ts
deploy/cdk/test/maintain-metadata/stack.test.ts
deploy/cdk/test/manifest-lambda/stack.test.ts
deploy/cdk/test/manifest-pipeline/stack.test.ts
deploy/cdk/test/multimedia-assets/multimedia-assets-stack.test.ts
deploy/cdk/yarn.lock

* Migrated tests from @aws-cdk/assert to @aws-cdk/assertions to prepare for migration to CDK 2.x

Esu 2081 migrate tests to assertions

---

deploy/cdk/lib/cdk-pipeline-deploy.ts
deploy/cdk/lib/static-host/pipeline-s3-sync.ts

* Added access to bucket starting with cdk*.  The marble pipelines now deploy correctly.

Fixed CDK2 bucket permissions

---

deploy/cdk/bin/codepipelines.ts
deploy/cdk/lib/cdk-pipeline-deploy.ts
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cdk/lib/image-processing/deployment-pipeline.ts
deploy/cdk/lib/maintain-metadata/deployment-pipeline.ts
deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts
deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
deploy/cdk/lib/multimedia-assets/deployment-pipeline.ts
deploy/cdk/lib/opensearch/deployment-pipeline.ts
deploy/cdk/lib/opensearch/opensearch-stack.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts

* Added dockerhub credentials to pipeline deployments to avoid error of "toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
* Bumped version of OpenSearch from 1.0 to 1.2 (which is what we're actually using in production)

Add dockerhub credentials

---

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts

These lines were found in production and are apparently necessary for the save portfolio resolver to work correctly. A change was made on an old branch on Oct 15, 2021, that was deployed to production (apparently), but never merged to master.
**Note:** 
Stale branch with same changes that was presumably deployed: https://github.com/ndlib/marble-blueprints/commit/d22455ae0cb0b127f454490ceeed60aac52951d1

Restore missing lines.

---

deploy/cdk/lib/foundation/foundation-stack.ts
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts
deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts
deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts
deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts
deploy/cdk/lib/multimedia-assets/deployment-pipeline.ts
deploy/cdk/lib/multimedia-assets/multimedia-assets-stack.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts
deploy/cdk/lib/static-host/static-host-stack.ts
deploy/cdk/test/maintain-metadata/stack.test.ts
deploy/cdk/test/manifest-lambda/stack.test.ts
deploy/cdk/test/manifest-pipeline/stack.test.ts
deploy/cdk/test/multimedia-assets/multimedia-assets-stack.test.ts

* Changed pipelines to grant access to create DNS entries for the hosted zones saved in parameter store.
* Changed stacks to create DNS entries in the hosted zones defined by hostedZoneTypes in combination with parameter store values.
* Changed to use CertificateArn from foundation-stack instead of certificate export
* Note: This is PR 2 of 3.  The final one will clean up residual DNS, certificate, and hostedZone items that are no longer needed.

Create DNS entries

---

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts
deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts
deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts

* With CDK version 2.43, ParameterType (from library aws-cdk-lib/aws-ssm) has been deprecated.  StringParameter will only retrieve STRING parameters, not SECURE_STRING parameters.
Since we're only storing STRING parameters anyway, I removed references to the deprecated ParameterType.

Removed Deprecated SSM Parameter Type

---

deploy/cdk/bin/codepipelines.ts
deploy/cdk/bin/services.ts
deploy/cdk/cdk.context.json
deploy/cdk/lib/cdk-pipeline-deploy.ts
deploy/cdk/lib/context-env.ts
deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts
deploy/cdk/lib/image-processing/deployment-pipeline.ts
deploy/cdk/lib/maintain-metadata/deployment-pipeline.ts
deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts
deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts
deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
deploy/cdk/lib/multimedia-assets/deployment-pipeline.ts
deploy/cdk/lib/multimedia-assets/multimedia-assets-stack.ts
deploy/cdk/lib/static-host/deployment-pipeline.ts
deploy/cdk/lib/static-host/static-host-stack.ts
deploy/cdk/test/multimedia-assets/multimedia-assets-stack.test.ts

* create parameter store values in stacks to export AWS api gateway and cloudfront names to later use for smoke tests
* added 'stage' and 'hostedZoneTypesTest' parameters to various stacks
Note:  These changes must be deployed before the next set of changes where we actually start using these values.

Make test stages private

---

deploy/cdk/cdk.context.json
deploy/cdk/lib/static-host/deployment-pipeline.ts

* Removed the smoke test from the test stage of static host deployments
* Test the prod stage using the DNS name instead of the cloudfront name stored in parameter store.

Modify website smoke tests

---

deploy/cdk/lib/static-host/deployment-pipeline.ts

* Alphabetized static-host parameters (so I can find them easier0
* Optionally create smoke test action only if we're creating public DNS entries.

change website smoke tests

---

deploy/cdk/lib/backup/backup-stack.ts
deploy/cdk/package.json
deploy/cdk/yarn.lock
src/unifiedEdgeLambda/package.json
src/unifiedEdgeLambda/yarn.lock

* changed to use the DynamoDB backup provided by esu-infrastructure
* updated packages
* After this is deployed, we'll need to come back and remove the BackupStack and all references to it.
* We will also need to delete the marbleb-prod-backup stack

Change dynamo backup
