deploy/cloudformation/iiif-service-pipeline.yml
60e173d990c24139beb9e382ec846f6339b6fbcb
Added CDBranchName parameter and changed the source stage to use the parameter instead of a constant 'master'
=> Parameterize the branch to observe

deploy/cloudformation/iiif-service-pipeline.yml, deploy/cloudformation/iiif-service.yml
Adding the post-deploy steps from ESU-707 to the image-server pipeline
=> ESU-705 add post-deploy steps for image server pipeline

deploy/cloudformation/static-host-pipeline.yml
This creates a new CodeBuild project and a new CodePipeline stage to leverage it. The new project runs the post-deploy action of updating the GitHub commit status.
- resolves #31
=> ESU-778 Post-Deploy Breakout

deploy/cloudformation/iiif-service-pipeline.yml, deploy/cloudformation/iiif-service.yml
Mostly I reverted the -k flag for no checking the ssl cert.
But I also fixed a variable that was passing the wrong url to the tests.
=> Revert newman test flags

deploy/cloudformation/manifest-pipeline-pipeline.yml
My typos and the weirdest missing permission.
=> Fix pipeline deploy

deploy/cloudformation/app-infrastructure.yml, deploy/cloudformation/iiif-service.yml, deploy/cloudformation/static-host.yml
Changes to add DNS registration with Route 53 if chosen using new parameter. Also removes option for SSL in all cases (now required).  All entities are in a Domain selected in the infrastructure build.
=> ESU-801 Add DNS registration

deploy/cloudformation/manifest-pipeline-pipeline.yml
Needed to add a permission to the pipeline to ensure deployment works.
=> Quick permission fix for pipeline

deploy/cloudformation/manifest-pipeline.yml
ECS will now handle image processing
=> MEL-137 removed lambda steps in favor of ECS

deploy/cloudformation/manifest-pipeline-pipeline.yml
The CodePipeline needs to be able to attach/detach policies on the DebugRole.
=> Fix pipeline permissions

deploy/cloudformation/manifest-pipeline.yml
update the step functions to have to the new format.  
There is now a choice based on the type csv or mets.
=> change to have new step functions

deploy/cloudformation/manifest-pipeline-pipeline.yml
So that it can run the python3 for the tests.
=> Change the image for codebuild

deploy/cloudformation/manifest-pipeline.yml
And add a variable to extend the time it looks back while this is not running daily
=> update lambda timeouts

deploy/cloudformation/manifest-pipeline.yml
This is the first step in specifying the layer version to use within the manifest data pipeline.
=> Parameterize sentry layer version

deploy/cloudformation/manifest-pipeline.yml
Updated the state machine to be the new sets of lambdas 
removed old lambdas
Added new lambda to process manifests serially.
=> update csv process to have new lambdas

deploy/cdk/bin/base.ts, deploy/cdk/cdk.json, deploy/cdk/lib/user-content/index.ts, deploy/cdk/package-lock.json, deploy/cdk/package.json
* This is the CDK code to create and deploy the [Marble User Content 
stack](https://github.com/ndlib/marble-user-content).
* It creates 3 dynamo tables, 1 lambda, and an API gateway.
* In order to use this in it's current state, it makes the assumption 
that you have both this repository and Marble User Content within the 
same parent directory. Lambda code path is: 
`../../../marble-user-content/src`
* Deploying this requires invoking AWS Vault or otherwise assuming 
credentials and running the following from the 
`marble-blueprints/deploy/cdk` directory: 
```
cdk deploy marble-user-content -c projectName=marble -c 
description=[DESCRIPTION] -c contact=[NAME] -c owner=[NAME]
```
=> MARBLE-595 Create CDK code for Marble User Content stack

deploy/cloudformation/manifest-pipeline.yml
Need to permissions for the task to read the images in the buckets.
=> add permissions to the rsbc bucket

deploy/cdk/cdk.json, deploy/cdk/lib/user-content/index.ts
Add missing CORS preflight check, so that `fetch` will work.
=> Add missing CORS preflight check

src/unifiedEdgeLambda/handler.js, src/unifiedEdgeLambda/handler.test.js, src/unifiedEdgeLambda/yarn.lock
We have a problem with some of the URLs with snite accessions numbers such as 
/item/1999.024
/item/1999.024.323
This only happens when you directly access the url.
=> update the edge lambda and tests.

deploy/cloudformation/manifest-pipeline-pipeline.yml, deploy/cloudformation/manifest-pipeline.yml
Added AlephExportLambdaFunction.
Added this function to StateMachineCreateCSVs.
Added StartHarvestAndCreateCSVRule to conditionally create a cron rule to start the step functions.  
The condition is named CreateHarvestAndCSVRule, which defaults to False, and is only set to True in manifest-pipeline-pipeline.yaml for Production through a parameter override.
=> Add aleph export

deploy/cloudformation/unified-static-host.yml
=> Update node runtime to latest supported

deploy/cloudformation/manifest-pipeline.yml
Added CurateExportLambdaFunction to StateMachineCreateCSVs.
Added additional Catches for lambda errors.
=> Add curate_export lambda

deploy/cloudformation/manifest-pipeline.yml
Modified manifest-pipeline.yml
- addedLoggingConfiguration to StateMachineCreateCSVs
- added to AllowStepFunctionLoggingPolicy statement to allow various privileges for logging.
=> added logging to StateMachineCreateCSVs

deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
The lambda was encountering a runtime issue with the sharp library. Had to change the build to use the lambda ci image. Also fixed a naming issue with the codebuilds, and added better approval messaging. Also fixed a bug with the lambda timeout override. Needed to be a string
=> Fix IIIF serverless build

deploy/cdk/bin/base.ts, deploy/cdk/cdk.context.json, deploy/cdk/lib/namespaced-policy.ts, deploy/cdk/lib/user-content/deployment-pipeline.ts, deploy/cdk/lib/user-content/user-content-stack.ts
MARBLE-825 Configure SSL certificates for user-content API
=> MARBLE-825 Configure SSL certificates for user-content API

deploy/cloudformation/manifest-pipeline.yml
* Added ability to loop over multiple iterations of museum export now that we have more museum items than can be harvested in the lambda timeout period.
=> Added museum looping to StateMachineCreateCSVs

deploy/cloudformation/manifest-pipeline.yml
* Changed references from StateMachineCreateCSVs to MarbleSourceSystemHarvest to more accurately describe what we're doing.
* Added creation of collections_api lambda
* Added step function to call lambda after creating standard_json from all source systems
=> Add collections api lambda

deploy/cloudformation/manifest-pipeline.yml
* Added creation of ObjectFilesApiLambdaFunction
* Added call to this new lambda from MarbleSourceSystemHarvest State Machine.
=> Added ObjectFilesApiLambdaFunction

deploy/cloudformation/manifest-pipeline-pipeline.yml, deploy/cloudformation/manifest-pipeline.yml
moving image processing to https://github.com/ndlib/marble-images
=> marble-1021

deploy/cdk/.eslintignore, deploy/cdk/.eslintrc.js, deploy/cdk/.gitignore, deploy/cdk/README.md, deploy/cdk/bin/base.ts, deploy/cdk/jest.config.js, deploy/cdk/lib/cdk-pipeline-deploy.ts, deploy/cdk/lib/foundation/foundation-stack.ts, deploy/cdk/lib/foundation/index.ts, deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts, deploy/cdk/lib/iiif-serverless/index.ts, deploy/cdk/lib/image-processing/deployment-pipeline.ts, deploy/cdk/lib/image-processing/images-stack.ts, deploy/cdk/lib/image-processing/index.ts, deploy/cdk/lib/image-processing/s3ToLambda.ts, deploy/cdk/lib/namespaced-policy.ts, deploy/cdk/lib/user-content/deployment-pipeline.ts, deploy/cdk/lib/user-content/index.ts, deploy/cdk/lib/user-content/user-content-stack.ts, deploy/cdk/package.json, deploy/cdk/test/foundation/stack.test.ts, deploy/cdk/test/helpers.ts, deploy/cdk/tslint.json, deploy/cdk/yarn.lock
The lack of good linting was bothering me, so I added eslint in. (Note that tslint is now deprecated, in favor of eslint's typescript support.) Most of these changes are just the result of letting eslint autofix formatting issues.
=> Add ESLint.

deploy/cdk/bin/base.ts, deploy/cdk/lib/elasticsearch/deployment-pipeline.ts, deploy/cdk/lib/elasticsearch/elastic-stack.ts
Steve notified me of a compilation error in elasticsearch stack/pipeline. He noticed that env/contextEnvName were not in the elasticsearch stack/pipeline. This fixes those issues and while I was in there I cleaned up some linter errors.
=> elasticsearch context env fix and linter fixes

deploy/cdk/bin/codepipelines.ts, deploy/cdk/cdk.context.json, deploy/cdk/lib/context-env.ts
This adds state change notifications to all code pipelines in production.
=> Add notifications

deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
This breaks out the unit tests for the app into a separate stage from
the test deploy. Unit tests can always be safely re-run, even if the
pipeline is stalled in a deploy stage. It also has a different set of
package dependencies from a production deploy, so it should be managed
in a separate environment.
Note: I still genuinely think this needs to be part of a CI pipeline which can 
be 100% done in the app's Github prior to merging into master, which is a 
separate cycle from a deployment pipeline. But, if we are going to add these 
here, it should be in a separate stage like this.
=> Fix manifest pipeline tests

deploy/cdk/bin/services.ts, deploy/cdk/cdk.context.json, deploy/cdk/lib/context-env.ts, deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts, deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts, deploy/cdk/lib/service-levels/service-levels-stack.ts, deploy/cdk/lib/user-content/user-content-stack.ts
This adds all of our defined SLOs for the marble services. In several
cases, had to add additional exports and things to point to the correct
resources in the metrics.
=> Add service level objectives

deploy/cdk/cdk.context.json, deploy/cdk/lib/dockerhub-image.ts, deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts, deploy/cdk/lib/static-host/deployment-pipeline.ts, deploy/cdk/lib/user-content/deployment-pipeline.ts
This adds our credentials to all of the CodeBuilds that pull the Newman
image from Dockerhub. This should fix our pull limits issue
=> Add Dockerhub authentication

deploy/cdk/cdk.context.json
Update cdk.context.json
* attempt to fix deployment for marble website after adding git submodule
* add submodule information
=> MARBLE-1359 Update context to recognize git submodule for sites/marble

deploy/cdk/cdk.context.json
to not have the s.
fix the git branch the pipeline is watching.
=> update inquisitions domain name

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql, deploy/cdk/package.json, deploy/cdk/test/maintain-metadata/stack.test.ts, deploy/cdk/yarn.lock
* Updated Schema
* Added new query to listFilesToProcess to report files needing processed.  If a date is supplied, list files processed before that date in addition to files not yet processed.  If no date is supplied, list files that have not yet been processed.
* Added new mutation to saveFileLastProcessedDate to capture when each file is processed.
* Added unit tests
=> Marble 1437 add file processing endpoints to maintain metadata

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql, deploy/cdk/lib/namespaced-policy.ts, deploy/cdk/package.json, deploy/cdk/test/maintain-metadata/stack.test.ts, deploy/cdk/yarn.lock
* Added query getFileToProcessRecord
* Added mutation to saveAdditionalNotesForWebsite
* Added nodes to ItemMetadata: additionalNotes, digitizationSource
* Added nodes to File: mediaResourceId and MediaServer.
* Added function expandSubjectTermsFunction which expands subject terms for an item.
* Added appropriate unit tests.
=> MARBLE 1485 Create subject terms pipeline resolver for Maintain Metadata

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts
* Ran into a bug when there are no subjects to expand (passing an empty array of key values resulted in an error).  A dynamo query is required in a pipeline resolver, so I'm passing a key that I know doesn't exist, so there are no results.
=> Fix Subject Term Expansion Bug

deploy/cdk/cdk.context.json, deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts, deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts
Related: ndlib/serverless-iiif#15
=> MARBLE-1192 Add cache parameters.

deploy/cdk/lib/static-host/deployment-pipeline.ts, deploy/cdk/lib/static-host/pipeline-s3-sync.ts
This time with me running yarn build.
=> Fix  a missing prop validation.

deploy/cdk/lib/maintain-metadata/schema.graphql, deploy/cdk/test/manifest-pipeline/stack.test.ts
* Added creationPlace to graphql schema for maintain-metadata
* Added back in more test fixtures for manifest-pipeline stack
=> Add creationPlace to maintain-metadata

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql, deploy/cdk/test/maintain-metadata/stack.test.ts
* Added physicalAccess to schema to allow Snite gallery to be available.
* Added removeDefaultImageForWebsite resolver.
=> MARBLE 1602 Remove default image from AppSync

deploy/cdk/bin/codepipelines.ts, deploy/cdk/lib/multimedia-assets/deployment-pipeline.ts, deploy/cdk/lib/multimedia-assets/index.ts, deploy/cdk/test/multimedia-assets/smokeTests.json
This pipeline simply sets up the bucket and cloudfront; it does not do anything to bring content into the bucket, as that has yet to be determined.
=> MARBLE-1632 Add pipeline for multimedia-assets.

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/namespaced-policy.ts
* Removed unused Resolver from AppSync
* Added cloudfront:ListTagsForResource permissions in namespaced-policy.ts
=> Removed unused Resolver from AppSync

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts
* Fixed a typo (toDynamoDbJson -> toDynamoDBJson impacting 6 resolvers
=> Fix AppSync Bug

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql, deploy/cdk/package.json, deploy/cdk/test/maintain-metadata/stack.test.ts, deploy/cdk/yarn.lock
* added additionalNotes parameter to saveCopyrightForWebsite resolver
* added optional storageSystem parameter to listFileGroups, listImageGroups, and listMediaGroups resolvers.
* removed saveAdditionalNotesForWebsite, listFileGroupsByStorageSystem, listImageGroupsByStorageSystem, and listMediaGroupsByStorageSystem resolvers.
* updated listFileGroupsForS3, listMediaGroupsForS3, and listImageGroupsForS3 to use filter for storageSystem.
* added resolvers for getImage, getImageGroup, getMedia, getMediaGroup
* updated tests
=> Update AppSync Resolvers

deploy/cdk/bin/services.ts, deploy/cdk/cdk.context.json, deploy/cdk/lib/context-env.ts, deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql, deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts, deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts, deploy/cdk/lib/manifest-pipeline/s3ToLambda.ts, deploy/cdk/test/maintain-metadata/stack.test.ts, deploy/cdk/test/manifest-lambda/stack.test.ts, deploy/cdk/test/manifest-pipeline/stack.test.ts
* Added copyMediaContentLambda to manifest-pipeline-stack.
* Added code to the manifest deployment-pipeline to only create the lambda in the prod stage of the prod environment.
=> Create lambda to copy Marble media content

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql, deploy/cdk/package.json, deploy/cdk/test/maintain-metadata/stack.test.ts, deploy/cdk/yarn.lock
* Added PortfolioCollectionCreatorResolver.
* Added to tests.
* Removed obsolete file resolvers and data types from AppSync
* Removed obsolete tests
=> Include Creator in AppSync Public Portfolio Collection information

deploy/cdk/bin/services.ts
This is to correct all SLOs that were exceeding what AWS has committed
to for the particular composition of services.
=> Adjust Availability SLOs

deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts, deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts
It has started failing on the update tests with 3.8.8 is not installed.  Updating to 3.8.10 to fix.
=> update python version.

deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts, deploy/cdk/lib/monitoring/dashboards-stack.ts, deploy/cdk/lib/static-host/static-host-stack.ts
Found several things that still aren't working fully with the dashboards. I likely won't have time to fix these, so I want to at least drop some notes somewhere for the next person who picks this up.
=> Just adding some monitoring TODO notes for the next person

deploy/cdk/bin/codepipelines.ts, deploy/cdk/bin/services.ts, deploy/cdk/lib/namespaced-policy.ts, deploy/cdk/lib/opensearch/deployment-pipeline.ts, deploy/cdk/lib/opensearch/index.ts, deploy/cdk/lib/opensearch/opensearch-stack.ts, deploy/cdk/lib/static-host/deployment-pipeline.ts, deploy/cdk/lib/types.ts
* Created new stacks for opensearch and opensearch-deployment-pipeline
* Currently, the deployment pipeline gets an error while deploying which I don't get in the test environment when deploying directly.  I need to try to deploy this in production so I can create a ticket with AWS to help me resolve the problem.
=> Upgrade elastic search to open search

deploy/cdk/cdk.context.json, deploy/cdk/lib/context-helpers.ts, deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts, deploy/cdk/lib/opensearch/deployment-pipeline.ts, deploy/cdk/lib/static-host/deployment-pipeline.ts, deploy/cdk/lib/static-host/pipeline-s3-sync.ts, deploy/cdk/package.json, deploy/cdk/test/iiif-serverless/iiif-serverless-stack.test.ts, deploy/cdk/yarn.lock
* Changed static-host to use only OpenSearch prod cluster
* Added authClient environment variables to static host
* Updated version of ndlib-cdk to latest version
=> Marble 2065 only use open search prod cluster

deploy/cdk/bin/codepipelines.ts, deploy/cdk/lib/opensearch/deployment-pipeline.ts, deploy/cdk/lib/static-host/deployment-pipeline.ts
* Removed deployment of OpenSearch test stack from OpenSearch deployment pipeline.ts
* Removed  references to the testOpenSearchStack from codepipelines.ts and static-host/deployment-pipeline.ts
=> Removed OpenSearch test stack

deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts, deploy/cdk/test/iiif-serverless/iiif-serverless-stack.test.ts
Reverts ndlib/marble-blueprints#355
=> Revert "refactor template to cdk"

deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts
Reverts ndlib/marble-blueprints#360
=> Revert "update iiif serverless build process"

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql
Create a special resolver that can change the privacy and highlighted/featured fields of any collection. Limit it's access to Library faculty/staff.
=> MARBLE-1617 Highlighted/Featured Collection mutation resolver

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql
Adding some additional fields that will hold base64 encoded strings that will be migrated to at a later time.
=> MARBLE-2102 Add duplicate fields for base64 migration

.github/workflows/ci.yml, deploy/cdk/lib/cdk-pipeline-deploy.ts, deploy/cdk/lib/static-host/pipeline-s3-sync.ts, deploy/cdk/package.json, deploy/cdk/yarn.lock, src/unifiedEdgeLambda/package.json, src/unifiedEdgeLambda/yarn.lock
* Changed from specifying specific node version to using "n stable" to specify the most current stable node version.  (AWS is deprecating nodejs 12 support for lambdas.)
* Update all packages
* renamed unifiedEdgeLambda to be a legal lambda name (no uppercase)
=> Updated Node Version

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/maintain-metadata/schema.graphql
* Added resolver to expand Portfolio Item
=> MARBLE 2095 expand portfolio item

deploy/cdk/lib/static-host/pipeline-s3-sync.ts
* Added GATSBY_OPENSEARCH_INDEX env variable
=> Add gatsby opensearch index

deploy/cdk/lib/cdk-pipeline-deploy.ts, deploy/cdk/lib/static-host/pipeline-s3-sync.ts, deploy/cdk/package.json, deploy/cdk/yarn.lock
* revert node to nodejs 16.x from "n stable"
* updated packages
=> revert node to nodejs 16.x

deploy/cdk/lib/cdk-pipeline-deploy.ts, deploy/cdk/lib/static-host/pipeline-s3-sync.ts
* Try another option to lock in nodejs 16.x
=> node 16 again

deploy/cdk/bin/services.ts, deploy/cdk/cdk.context.json, deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts, deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts, deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts, deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts, deploy/cdk/lib/multimedia-assets/deployment-pipeline.ts, deploy/cdk/lib/multimedia-assets/multimedia-assets-stack.ts, deploy/cdk/lib/static-host/deployment-pipeline.ts, deploy/cdk/lib/static-host/static-host-stack.ts, deploy/cdk/test/manifest-lambda/stack.test.ts, deploy/cdk/test/multimedia-assets/multimedia-assets-stack.test.ts
* Changed smoke tests to use AWS names
* Changed DNS creation to private hosted zones for dev environment and test stage deployment in production environment
* Fixed tests
=> make test stage private part 2

deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts, deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts
* removed 'https://' from stored url.
=> remove unwanted https

deploy/cdk/bin/codepipelines.ts, deploy/cdk/cdk.context.json, deploy/cdk/lib/cdk-pipeline-deploy.ts, deploy/cdk/lib/iiif-serverless/iiif-serverless-stack.ts, deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts, deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts, deploy/cdk/lib/static-host/deployment-pipeline.ts, deploy/cdk/lib/static-host/pipeline-s3-sync.ts, deploy/cdk/lib/static-host/static-host-stack.ts, deploy/cdk/package.json, deploy/cdk/yarn.lock
* Updated to STANDARD_6_0 image
* Added Okta secrets to cdk.context.json, and passed these to static-host-pipeline and pipeline-s3-sync
* Alphabetized cdk.context.json so I can find things easier
* Updated to nodejs 18.x for redirect lambdas
=> Update linux image

deploy/cdk/README.md, deploy/cdk/lib/static-host/pipeline-s3-sync.ts
* revert static host deployment to node 16
=> revert static host deployment to node 16

deploy/cdk/lib/maintain-metadata/maintain-metadata-stack.ts, deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts, deploy/cdk/lib/manifest-lambda/manifest-lambda-stack.ts, deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts, deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts
* Attempting to fix pipelines for manifest-lambda-deployment and manifest-pipeline-deployment
=> Bump Python Versions

deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts, deploy/cdk/test/manifest-pipeline/stack.test.ts
* Temporarily (for one week) disable museum export
=> disable museum export

deploy/cdk/lib/manifest-pipeline/manifest-pipeline-stack.ts, deploy/cdk/package.json, deploy/cdk/test/manifest-pipeline/stack.test.ts, deploy/cdk/yarn.lock
* re-enabled museum export
* fixed tests
* updated packages
=> re-enable museum export

.github/workflows/ci.yml, deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts, deploy/cdk/package.json, deploy/cdk/yarn.lock, src/unifiedEdgeLambda/yarn.lock
* Set buildImage to Standard_6_0 (had defaulted to Standard 1.0)
* Updated packages
=> Upgrade IIF CodeBuild

deploy/cdk/bin/codepipelines.ts, deploy/cdk/cdk.context.json, deploy/cdk/lib/context-env.ts, deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts, deploy/cdk/lib/image-processing/deployment-pipeline.ts, deploy/cdk/lib/maintain-metadata/deployment-pipeline.ts, deploy/cdk/lib/manifest-lambda/deployment-pipeline.ts, deploy/cdk/lib/manifest-pipeline/deployment-pipeline.ts, deploy/cdk/lib/multimedia-assets/deployment-pipeline.ts, deploy/cdk/lib/static-host/deployment-pipeline.ts, deploy/cdk/package.json, deploy/cdk/yarn.lock
* changed to use slackNotifyTopicOutput instead of slackNotifyStackName, and changed all corresponding code
* updated packages
=> change slack notifications
